name: "Compliance"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  compliance:
    uses: OpenSource-Communities/.github/.github/workflows/compliance.yml@main
